version: "3"

services:
  webdefault:
    container_name: "nginxDev"
    image: nginx
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - ./www:/usr/share/nginx/html
    restart: always
