services:
  nginxproxy:
    container_name: "nginxproxy"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      ### required for Let's Encrypt certificates
      - certs:/etc/nginx/certs:ro
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - MainNetwork
      - AppNetwork
      # - LeagueAbuserNetwork

  letsencrypt:
    container_name: "letsencrypt"
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=sandro.spengler@web.de
      - NGINX_PROXY_CONTAINER=nginxproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
    networks:
      - MainNetwork
    restart: always

  webdefault:
    container_name: "nginxMain"
    image: nginx
    environment:
      - VIRTUAL_HOST=xxx
      - LETSENCRYPT_HOST=xxx
    networks:
      - AppNetwork
    restart: always

  # leaugeabuser:
  #   container_name: "nginxLeague"
  #   image: nginx
  #   environment:
  #     - VIRTUAL_HOST=xxx
  #     - LETSENCRYPT_HOST=xxx
  #   networks:
  #     - LeagueAbuserNetwork
  #   restart: always

networks:
  MainNetwork:
  AppNetwork:
  # LeagueAbuserNetwork:

volumes:
  nginx_certs:
  nginx_vhosts:
  nginx_html:
  certs:
