version: "3"

services:
  nginxproxy:
    container_name: "nginxproxy"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      ### required for Let's Encrypt certificates
      - ~/LetsEncrypt/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html

  letsencrypt:
    container_name: "letsencrypt"
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=sandro.spengler@web.de
      - NGINX_PROXY_CONTAINER=nginxproxy
    volumes:
      - ~/LetsEncrypt/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    restart: always

volumes:
  #### NGINX reverse proxy container volumes
  nginx_certs:
  nginx_vhosts:
  nginx_html:
